### ISSUE TITLE
`ActiveText` Doesn't Update Correctly Based on Item State

### ISSUE THREAD

**Issue by Raito-95** [vinaghost/TravianBotSharp#101]
#### Description:
Before clicking the button, `ActiveText` always shows "Active" regardless of whether the selected item is red or green. After clicking the button once, `ActiveText` changes to "Deactive" and stays like that for all items, even when switching between red (inactive) and green (active) items.

#### Steps to Reproduce:
1. Open the farm list.
2. Select any item — regardless of the item's color (red or green), the button shows "Active."
3. Click the button — the button now shows "Deactive."
4. Switch to another item, either red or green — the button still shows "Deactive," even for red (inactive) items.

#### Expected Behavior:
`ActiveText` should update based on the selected item's color:
- Red (inactive) items should show "Active."
- Green (active) items should show "Deactive."

#### Actual Behavior:
- Initially, all items (both red and green) show "Active."
- After clicking the button, all items show "Deactive," regardless of their color.

#### Suggested Fix:
Consider updating `ActiveText` whenever the selected item changes. Something like this could work:

```csharp
this.WhenAnyValue(x => x.FarmLists.SelectedItem)
    .Where(selectedItem => selectedItem != null)
    .Subscribe(selectedItem =>
    {
        var color = selectedItem.Color;
        ActiveText = _activeTexts[color];
    });
```
This will ensure that ActiveText updates correctly based on the selected item's color.

Thanks!

**Comment by vinaghost** [comment]
thanks for you report
i will check and fix this issue in next patch
