### ISSUE TITLE
[BUG] The bot ends when trying to upgrade the next build task when one is already in progress

### ISSUE THREAD

**Issue by asaura08** [vinaghost/TravianBotSharp#78]
12:44:56 [ERR] Cannot find button [upgrade] . Bot must retry
from file: D:\a\TravianBotSharp\TravianBotSharp\MainCore\Tasks\UpgradeBuildingTask.cs [128]
12:44:56 [WRN] Retry 1 for Upgrade building in Aldea de X
12:45:03 [INF] Build "ClayPit" to level 1 at location 16
12:45:03 [WRN] There is something wrong.
12:45:03 [ERR] Cannot find button [upgrade] . Bot must retry
from file: D:\a\TravianBotSharp\TravianBotSharp\MainCore\Tasks\UpgradeBuildingTask.cs [128]
12:45:03 [WRN] Retry 2 for Upgrade building in Aldea de X
12:45:09 [INF] Build "ClayPit" to level 1 at location 16
12:45:09 [WRN] There is something wrong.
12:45:09 [ERR] Cannot find button [upgrade] . Bot must retry
from file: D:\a\TravianBotSharp\TravianBotSharp\MainCore\Tasks\UpgradeBuildingTask.cs [128]
12:45:09 [WRN] Retry 3 for Upgrade building in Aldea de X
12:45:16 [INF] Build "ClayPit" to level 1 at location 16
12:45:16 [INF] Upgrade building in Aldea de X is finished
12:45:16 [WRN] Cannot find button [upgrade] . Bot must retry
from file: D:\a\TravianBotSharp\TravianBotSharp\MainCore\Tasks\UpgradeBuildingTask.cs [128]

**Comment by vinaghost** [comment]
fixed in newest release
