### ISSUE TITLE
Bot must stop!!!

### ISSUE THREAD

**Issue by MrTnx1994** [vinaghost/TravianBotSharp#79]
from file: D:\a\TravianBotSharp\TravianBotSharp\MainCore\Services\ChromeBrowser.cs [372]
from file: D:\a\TravianBotSharp\TravianBotSharp\MainCore\Commands\Features\UpgradeBuilding\SpecialUpgradeCommand.cs [81]
from file: D:\a\TravianBotSharp\TravianBotSharp\MainCore\Tasks\UpgradeBuildingTask.cs [123]

Hello
I always give the account program to the robot after a few hours
or minutes, the bot stops automatically and there is an error in the log.
This case is not related to an account and usually and always occurs and exists.

**Comment by vinaghost** [comment]
fixed in newest release
