### ISSUE TITLE
Issue with "Move to Top" and "Move to Bottom" Logic

### ISSUE THREAD

**Issue by Raito-95** [vinaghost/TravianBotSharp#85]
Hi,

I noticed that the "Move to Top" and "Move to Bottom" functionality in the current implementation isn't working as expected. Instead of moving the selected item directly to the top or bottom and shifting the other items accordingly, it seems to just swap the selected item with the one at the top or bottom.

This means that if I choose to move an item to the top, it ends up swapping places with the current top item, rather than shifting the entire list down and placing the selected item at the top. The same issue occurs with the "Move to Bottom" functionality.

It would be great if this could be adjusted to move the item directly to the desired position while shifting the other items accordingly.

Thanks!

**Comment by vinaghost** [comment]
congratulations! You found this after 9 months =))) 
i aware about this but no body report so I just leave it there
