### ISSUE TITLE
Allow bot to use hero resources if resources are low.

### ISSUE THREAD

**Issue by Campbell-hash-f** [vinaghost/TravianBotSharp#92]
please implement a fall back to use hero inventory resources, after failing a task with "resources low".

I saw an old issue https://github.com/vinaghost/TravianBotSharp/issues/21 that points to the same issue, and as i can see the feature does not exists currently in the current version.

**Comment by vinaghost** [comment]
huh it works on my side

**Comment by Campbell-hash-f** [comment]
will be closed in reference to  https://github.com/vinaghost/TravianBotSharp/issues/93#issuecomment-2348403202
