### ISSUE TITLE
Auto collect hero rewards

### ISSUE THREAD

**Issue by Campbell-hash-f** [vinaghost/TravianBotSharp#93]
as a follow up on (https://github.com/vinaghost/TravianBotSharp/issues/92), please add an option that use could allow the bot to automatically collect the reward resources. 

this feature minimizes the uer interaction with bot, specially after setteling a new village.

**Comment by vinaghost** [comment]
this feature was implemented [here](https://github.com/vinaghost/TravianBotSharp/blob/main/MainCore/Tasks/ClaimQuestTask.cs )
and it get call [here](https://github.com/vinaghost/TravianBotSharp/blob/main/MainCore/Notification/Handlers/Trigger/TriggerClaimQuestTask.cs)

**Comment by Campbell-hash-f** [comment]
yes you are right, just could not find the settings for it in the UI, thanks for you explanation.

will leave a picture for the one like me have visual problems :))

<img width="666" alt="Bildschirmfoto 2024-09-13 um 10 49 40" src="https://github.com/user-attachments/assets/f7ccc714-809c-49bb-ad51-624660436446">


will colose the issue
